apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1" # default value for: sidecar.datasources.label
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://kube-prometheus-stack-prometheus.monitoring:9090/
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
    - name: Cloudwatch
      type: cloudwatch
      jsonData:
        authType: default
        defaultRegion: us-east-1
