apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nginx
  interval: 1m0s
  values:
    global:
      image:
        registry: registry.k8s.io
    controller:
      name: controller
      enableAnnotationValidations: true
      image:
        chroot: false
        image: ingress-nginx/controller
        tag: "v1.12.1"
      containerPort:
        http: 80
        https: 443
      service:
        enabled: true
        external:
          enabled: true
        type: LoadBalancer
