apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nginx
  interval: 1m0s
  values:
    global:
      image:
        registry: registry.k8s.io
    controller:
      service:
        type: NodePort
        external:
          enabled: true
        nodePorts:
          http: 30080
          https: 30443
